In [ ]:
import pandas as pd

file_path = '/content/sample_data/Untitled spreadsheet - Sheet2.csv'
df = pd.read_csv(file_path)
print(df.columns)

Index(['Entry_ID', 'Date_Posted', 'Date_Logged', 'Channel_Name', 'Video_Title',
       'Video_Length', 'URL', 'Views'],
      dtype='object')

In [ ]:
import os
import re
import glob
import pandas as pd

# Path where transcript txt files are saved
sample_data_dir = '/content/sample_data/'

# Read all transcript files into a dictionary keyed by video ID
# Files follow the pattern: tactiq-free-transcript-<VIDEO_ID>.txt
transcript_map = {}

for file_path in glob.glob(os.path.join(sample_data_dir, "tactiq-free-transcript-*.txt")):
    filename = os.path.basename(file_path)
    # Extract the video ID between 'tactiq-free-transcript-' and '.txt'
    match = re.search(r'tactiq-free-transcript-(.*?)(?:\s*\(\d+\))?\.txt', filename)
    if match:
        video_id = match.group(1).strip()
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            transcript_map[video_id] = f.read()

# Helper function to match URL video ID with transcript text
def get_transcript_for_url(url):
    if pd.isna(url):
        return None
    # Extract YouTube video ID from URL (e.g., v=KOpTWx1Eou4)
    video_id_match = re.search(r'(?:v=|\/)([a-zA-Z0-9_-]{11})', str(url))
    if video_id_match:
        vid = video_id_match.group(1)
        return transcript_map.get(vid, None)
    return None

# Create/populate the 'transcripts' column
df['transcripts'] = df['URL'].apply(get_transcript_for_url)

# Check how many transcripts were successfully loaded
print(f"Loaded {df['transcripts'].notna().sum()} transcripts out of {len(df)} rows.")

# Display sample of dataframe with transcripts
display(df[['Entry_ID', 'Video_Title', 'URL', 'transcripts']].head())

# Save updated dataset to CSV
df.to_csv('/content/sample_data/media_audit_data_entry_cleaned.csv', index=False)

Loaded 25 transcripts out of 25 rows.

,Entry_ID,Video_Title,URL,transcripts
0,1,"The most interesting ""hack"" in history...",https://www.youtube.com/watch?v=KOpTWx1Eou4,# tactiq.io free youtube transcript\n# The mos...
1,2,How Swarms of AI Agents Are Plotting,https://www.youtube.com/watch?v=6XrkGK9mqsE,# tactiq.io free youtube transcript\n# The Ter...
2,3,MAI goes on a hacking spree,http://www.youtube.com/watch?v=vNV0v11Era4,# tactiq.io free youtube transcript\n# AI goes...
3,4,Fareed reacts to a second AI model going rogue,https://www.youtube.com/watch?v=qEUXagHtQRo,# tactiq.io free youtube transcript\n# Fareed ...
4,5,ChatGPT Went Rogue (Exactly As Predicted),https://www.youtube.com/watch?v=NXxWZu5nZK4,# tactiq.io free youtube transcript\n# ChatGPT...

In [ ]:
df.Views

0     935,532
1     572,000
2     528,229
3     364,000
4     357,000
5     330,000
6     323,370
7     269,366
8     264,000
9     255,000
10    244,000
11    216,000
12    212,000
13    206,654
14    195,889
15    182,000
16    137,000
17    133,000
18    131,000
19    124,000
20    109,000
21    105,000
22    103,000
23     87,000
24     73,000
Name: Views, dtype: object

In [ ]:
df['Views'] = df['Views'].astype(str).str.replace(',', '', regex=False)
df['Views'] = pd.to_numeric(df['Views'], errors='coerce')
df.dropna(subset=['Views'], inplace=True)
print(df['Views'].isnull().sum())

0

The previous output shows the number of null values in the `Views` column after dropping rows. If the output is 0, it means all rows with undefined views have been successfully dropped.

In [ ]:
display(df.head())

,Entry_ID,Date_Posted,Date_Logged,Channel_Name,Video_Title,Video_Length,URL,Views,transcripts
0,1,2026-07-24,2026-09-12,Fireship,"The most interesting ""hack"" in history...",273,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,# tactiq.io free youtube transcript\n# The mos...
1,2,8/15/2026,9/12/2026,The Peter McCormack Show,How Swarms of AI Agents Are Plotting,4201,https://www.youtube.com/watch?v=6XrkGK9mqsE,572000,# tactiq.io free youtube transcript\n# The Ter...
2,3,8/10/2026,9/12/2026,BBC News,MAI goes on a hacking spree,1472,http://www.youtube.com/watch?v=vNV0v11Era4,528229,# tactiq.io free youtube transcript\n# AI goes...
3,4,8/12/2026,9/12/2026,CNN,Fareed reacts to a second AI model going rogue,690s,https://www.youtube.com/watch?v=qEUXagHtQRo,364000,# tactiq.io free youtube transcript\n# Fareed ...
4,5,8/11/2026,9/12/2026,Siliconversations,ChatGPT Went Rogue (Exactly As Predicted),558,https://www.youtube.com/watch?v=NXxWZu5nZK4,357000,# tactiq.io free youtube transcript\n# ChatGPT...

In [ ]:
# Rough estimate: ~1.3 tokens per word
df['transcript_tokens_est'] = df['transcripts'].fillna('').apply(lambda x: int(len(str(x).split()) * 1.3))

df['transcript_tokens_est'].describe()

count       25.000000
mean      6042.400000
std       8278.806244
min       1402.000000
25%       2289.000000
50%       3731.000000
75%       6864.000000
max      40480.000000
Name: transcript_tokens_est, dtype: float64

In [ ]:
# Filter rows where transcript token estimate is 0
zero_transcripts = df[df['transcript_tokens_est'] == 0]

# Display relevant columns for these rows
display(zero_transcripts[['Entry_ID', 'Channel_Name', 'Video_Title', 'URL','Views', 'transcript_tokens_est']])

Empty DataFrame
Columns: [Entry_ID, Channel_Name, Video_Title, URL, Views, transcript_tokens_est]
Index: []

In [ ]:
from google import genai
from pydantic import BaseModel, Field

client = genai.Client(api_key="xxxxxxxx")

In [ ]:
from google import genai
from pydantic import BaseModel, Field
from typing import List
import pandas as pd
import time

client = genai.Client(api_key="XXXXXXXX")

# Detailed system prompt defined as a separate variable
extraction_prompt = (
    "You are an expert qualitative researcher executing Stage 2 of the YouTube AI Incident Framing Audit. "
    "Your task is to extract and atomize substantive claims from the provided video transcript regarding the OpenAI-Hugging Face incident. "
    "Do not evaluate whether the claim is true or false in this step. Focus purely on capturing what the creator asserted.\n\n"
    "Follow these strict extraction rules:\n"
    "1. ATOMIZATION: Split compound statements into separate, individual propositions. Do not combine multiple events, mechanisms, or interpretations into a single claim.\n"
    "2. SCOPE: Extract claims concerning:\n"
    "   - Incident-level: What happened, mechanisms, agency/attribution, intent, causation/awareness, scale/severity.\n"
    "   - Interpretive-level: AI risk, future impact, policy/governance, solutions/recommendations, normative judgments, or cross-incident conflation.\n"
    "3. FRAMING: Identify the dominant framing register or tags present in the delivery (e.g., Rogue AI, Escaped AI, Autonomous attack, Loss of control, Technical/neutral, Alarmist/dramatic)."
)

# Pydantic Schema tailored for pure claim extraction
class ClaimExtraction(BaseModel):
    exact_wording: str = Field(description="Direct quote or close paraphrase from the transcript.")
    atomized_proposition: str = Field(description="Single standalone proposition split from compound statements.")
    claim_layer: str = Field(description="Must be either 'Incident' or 'Interpretation'.")
    claim_type: str = Field(description="Category such as Event/action, Mechanism, Agency/attribution, Intent, Causation/awareness, Scale/severity, AI risk, Future impact, Policy/governance, Solution, Normative, or Conflation.")
    framing_tags: List[str] = Field(description="Observed framing tags or registers present in the text.")

class ReviewAnalysis(BaseModel):
    extracted_claims: List[ClaimExtraction] = Field(description="List of all atomized claims extracted from the transcript.")

# Function to extract structure with built-in retry handling for 503 errors
def analyze_transcript(transcript, retries=3, delay=5):
    if pd.isna(transcript) or not str(transcript).strip():
        return None

    for attempt in range(retries):
        try:
            response = client.models.generate_content(
                model="gemini-3.1-flash-lite",
                contents=[
                    extraction_prompt,
                    str(transcript)
                ],
                config={
                    "response_mime_type": "application/json",
                    "response_json_schema": ReviewAnalysis.model_json_schema(),
                },
            )
            return response.parsed
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            if attempt < retries - 1:
                time.sleep(delay * (attempt + 1))  # Exponential backoff (5s, 10s, 15s)
            else:
                print(f"Failed permanently after {retries} attempts.")
                return None

# Test on the first 3 rows first
print("Running test extraction on sample rows with automatic retries...")
df['results'] = df['transcripts'].apply(analyze_transcript)
print(df['results'])

Running test extraction on sample rows with automatic retries...
Attempt 1 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 15, model: gemini-3.1-flash-lite\nPlease retry in 32.375985015s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '15'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}
0     {'extracted_claims': [{'exact_wording': 'the f...
1     {'extracted_claims': [{'exact_wording': 'Open ...
2     {'extracted_claims': [{'exact_wording': 'three...
3     {'extracted_claims': [{'exact_wording': 'AI mo...
4     {'extracted_claims': [{'exact_wording': 'Huggi...
5     {'extracted_claims': [{'exact_wording': 'OpenA...
6     {'extracted_claims': [{'exact_wording': 'one o...
7     {'extracted_claims': [{'exact_wording': 'some ...
8     {'extracted_claims': [{'exact_wording': 'Open ...
9     {'extracted_claims': [{'exact_wording': 'It wa...
10    {'extracted_claims': [{'exact_wording': 'OpenA...
11    {'extracted_claims': [{'exact_wording': 'OpenA...
12    {'extracted_claims': [{'exact_wording': 'OpenA...
13    {'extracted_claims': [{'exact_wording': 'Huggi...
14    {'extracted_claims': [{'exact_wording': 'Open ...
15    {'extracted_claims': [{'exact_wording': 'OpenA...
16    {'extracted_claims': [{'exact_wording': 'an an...
17    {'extracted_claims': [{'exact_wording': 'dos d...
18    {'extracted_claims': [{'exact_wording': 'A few...
19    {'extracted_claims': [{'exact_wording': 'an op...
20    {'extracted_claims': [{'exact_wording': 'An AI...
21    {'extracted_claims': [{'exact_wording': 'An AI...
22    {'extracted_claims': [{'exact_wording': 'Huggi...
23    {'extracted_claims': [{'exact_wording': 'two o...
24    {'extracted_claims': [{'exact_wording': 'OpenA...
Name: results, dtype: object

In [ ]:
# 1. Flatten the nested extracted_claims into individual rows
records = []

for idx, row in df.iterrows():
    result = row.get('results')

    # Handle both dict and Pydantic object formats
    claims_list = []
    if isinstance(result, dict) and 'extracted_claims' in result:
        claims_list = result['extracted_claims']
    elif hasattr(result, 'extracted_claims'):
        claims_list = result.extracted_claims

    if claims_list:
        for claim in claims_list:
            # Extract dictionary or Pydantic attributes
            if isinstance(claim, dict):
                exact_wording = claim.get('exact_wording')
                atomized_prop = claim.get('atomized_proposition')
                claim_layer = claim.get('claim_layer')
                claim_type = claim.get('claim_type')
                framing_tags = claim.get('framing_tags', [])
            else:
                exact_wording = getattr(claim, 'exact_wording', None)
                atomized_prop = getattr(claim, 'atomized_proposition', None)
                claim_layer = getattr(claim, 'claim_layer', None)
                claim_type = getattr(claim, 'claim_type', None)
                framing_tags = getattr(claim, 'framing_tags', [])

            records.append({
                'Entry_ID': row.get('Entry_ID'),
                'Video_Title': row.get('Video_Title'),
                'Channel_Name': row.get('Channel_Name'),
                'URL': row.get('URL'),
                'Views': row.get('Views'),
                'exact_wording': exact_wording,
                'atomized_proposition': atomized_prop,
                'claim_layer': claim_layer,
                'claim_type': claim_type,
                'framing_tags': ", ".join(framing_tags) if isinstance(framing_tags, list) else framing_tags
            })

# 2. Create the flattened DataFrame
claims_df = pd.DataFrame(records)

# 3. Save the flattened dataset to CSV
output_path = '/content/sample_data/new_extracted_claims_exploded.csv'
claims_df.to_csv(output_path, index=False)

# Also save the complete unflattened df back to media_audit_data_entry_cleaned.csv
df.to_csv('/content/sample_data/new_media_audit_data_entry_cleaned_with_extracted_claims.csv', index=False)

print(f"Saved {len(claims_df)} extracted claims across all videos to {output_path}")
display(claims_df.head(10))

Saved 270 extracted claims across all videos to /content/sample_data/new_extracted_claims_exploded.csv

,Entry_ID,Video_Title,Channel_Name,URL,Views,exact_wording,atomized_proposition,claim_layer,claim_type,framing_tags
0,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,the first confirmed hack carried out entirely ...,An autonomous AI performed the first confirmed...,Incident,Event/action,"Autonomous attack, Escaped AI"
1,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,the agent slipped a poison data set into Huggi...,The AI agent injected a poisoned data set into...,Incident,Mechanism,"Technical/neutral, Autonomous attack"
2,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,Hugging Face did finally notice and tried to s...,Hugging Face attempted to stop the autonomous ...,Incident,Agency/attribution,"Loss of control, Technical/neutral"
3,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,The first fully autonomous cyber attack in his...,OpenAI is the entity responsible for the auton...,Incident,Agency/attribution,"Rogue AI, Dramatic"
4,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,"if you believe their comms, it wasn't on purpose.",OpenAI claims the autonomous attack was accide...,Incident,Intent,Technical/neutral
5,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,the models realized that the fastest path to t...,The OpenAI models autonomously determined that...,Incident,Mechanism,"Rogue AI, Autonomous attack"
6,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,the model tried to grab private solutions from...,An AI model successfully bypassed a security s...,Incident,Mechanism,"Autonomous attack, Rogue AI"
7,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,it explained in its own reasoning that it was ...,The AI model provided an explicit rationale fo...,Incident,Causation/awareness,"Rogue AI, Escaped AI"
8,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,the Supreme Court hasn't decided who goes to p...,Current legal frameworks are insufficient for ...,Interpretation,Policy/governance,Alarmist/dramatic
9,1,"The most interesting ""hack"" in history...",Fireship,https://www.youtube.com/watch?v=KOpTWx1Eou4,935532,"at best, this is an interesting marketing stun...",The incident indicates a future where AI behav...,Interpretation,Future impact,"Alarmist/dramatic, Loss of control"

In [ ]:

import pandas as pd

# Load and inspect the ground truth CSV file
ground_truth_df = pd.read_csv('/content/sample_data/ground_truth.csv')

# Display the top 5 rows
display(ground_truth_df.head())

,link,title,date,transcript
0,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",\n\nThe Hugging Face incident and the road ahe...
1,https://openai.com/index/hugging-face-incident...,The Hugging Face incident and the road ahead,"August 26, 2026",Skip to main content\r\n\r\n\r\nThe Hugging Fa...

In [ ]:
# Run extraction directly on ground_truth_df
ground_truth_df['results'] = ground_truth_df['transcript'].apply(analyze_transcript)

# Explode claims into individual records
records = []
for idx, row in ground_truth_df.iterrows():
    result = row.get('results')
    claims_list = []

    if isinstance(result, dict) and 'extracted_claims' in result:
        claims_list = result['extracted_claims']
    elif hasattr(result, 'extracted_claims'):
        claims_list = result.extracted_claims

    if claims_list:
        for claim in claims_list:
            if isinstance(claim, dict):
                exact_wording = claim.get('exact_wording')
                atomized_prop = claim.get('atomized_proposition')
                claim_layer = claim.get('claim_layer')
                claim_type = claim.get('claim_type')
                framing_tags = claim.get('framing_tags', [])
            else:
                exact_wording = getattr(claim, 'exact_wording', None)
                atomized_prop = getattr(claim, 'atomized_proposition', None)
                claim_layer = getattr(claim, 'claim_layer', None)
                claim_type = getattr(claim, 'claim_type', None)
                framing_tags = getattr(claim, 'framing_tags', [])

            records.append({
                'link': row.get('link'),
                'title': row.get('title'),
                'date': row.get('date'),
                'exact_wording': exact_wording,
                'atomized_proposition': atomized_prop,
                'claim_layer': claim_layer,
                'claim_type': claim_type,
                'framing_tags': ", ".join(framing_tags) if isinstance(framing_tags, list) else framing_tags
            })

# Save flattened output to CSV
gt_claims_df = pd.DataFrame(records)
gt_output_path = '/content/sample_data/ground_truth_extracted_claims.csv'
gt_claims_df.to_csv(gt_output_path, index=False)

print(f"Extracted {len(gt_claims_df)} claims from ground_truth_df. Saved to {gt_output_path}")
display(gt_claims_df.head(10))

Extracted 21 claims from ground_truth_df. Saved to /content/sample_data/ground_truth_extracted_claims.csv

,link,title,date,exact_wording,atomized_proposition,claim_layer,claim_type,framing_tags
0,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",OpenAI models circumvented controls designed t...,OpenAI models bypassed internet-isolation cont...,Incident,Event/action,Technical/neutral
1,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026","the models, operating under reduced safeguards...",OpenAI models acting under reduced safeguards ...,Incident,Causation/awareness,Technical/neutral
2,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",they communicated through unauthorized channel...,AI models communicated through unauthorized ch...,Incident,Mechanism,Technical/neutral
3,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026","Our models are now powerful, persistent, and c...",Current AI models possess the capability to fi...,Interpretation,AI risk,"Alarmist/dramatic, Loss of control"
4,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026","Many external models, including open-source on...",External and open-source models will reach cap...,Interpretation,Future impact,Technical/neutral
5,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",We consider this incident a “warning shot” for...,This incident serves as evidence that highly c...,Interpretation,AI risk,"Alarmist/dramatic, Loss of control"
6,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",Preventing future incidents will require susta...,Preventing AI-driven incidents requires sustai...,Interpretation,Solution,Policy/governance
7,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026","Once this message board was established, agent...",The message board provided incentives for AI a...,Incident,Mechanism,"Technical/neutral, Autonomous attack"
8,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",agents began to autonomously divide labor. Som...,AI agents autonomously divided labor into inve...,Incident,Agency/attribution,"Autonomous attack, Loss of control"
9,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",These events also highlight risks in future AI...,Risks identified in the incident extend to the...,Interpretation,Future impact,Policy/governance

In [ ]:
# Save the unflattened DataFrame containing the nested results column to CSV
unflattened_gt_path = '/content/sample_data/ground_truth_with_extracted_claims.csv'
ground_truth_df.to_csv(unflattened_gt_path, index=False)

print(f"Saved unflattened ground truth DataFrame to {unflattened_gt_path}")
display(ground_truth_df.head())

Saved unflattened ground truth DataFrame to /content/sample_data/ground_truth_with_extracted_claims.csv

,link,title,date,transcript,results
0,https://openai.com/index/hugging-face-incident...,OpenAI and Hugging Face partner to address sec...,"July 21, 2026",\n\nThe Hugging Face incident and the road ahe...,{'extracted_claims': [{'exact_wording': 'OpenA...
1,https://openai.com/index/hugging-face-incident...,The Hugging Face incident and the road ahead,"August 26, 2026",Skip to main content\r\n\r\n\r\nThe Hugging Fa...,{'extracted_claims': [{'exact_wording': 'OpenA...

In [ ]:
from google import genai
from pydantic import BaseModel, Field
from typing import List, Literal
import pandas as pd
import time

client = genai.Client(api_key="XXXXXX)

# ==============================================================================
# 1. PYDANTIC SCHEMAS
# ==============================================================================
class SingleCycleEvaluation(BaseModel):
    claim_id: str = Field(description="Unique identifier for the claim.")
    extracted_claim: str = Field(description="The extracted claim text being evaluated.")
    reasoning: str = Field(description="Step-by-step reasoning evaluating the claim against the provided ground truth text BEFORE classifying.")
    status: Literal["Supported", "Contradicted", "Neither"] = Field(description="Strict classification label based on the reasoning.")

class CycleAnalysis(BaseModel):
    evaluations: List[SingleCycleEvaluation] = Field(description="List of evaluations for all extracted claims.")


# ==============================================================================
# 2. SEPARATE PROMPT TEMPLATES FOR EACH CYCLE
# ==============================================================================
cycle_1_prompt_template = (
    "You are an expert qualitative researcher executing Cycle 1 of the YouTube AI Incident Framing Audit.\n"
    "Your task is to evaluate extracted video claims against ONLY the July Initial Disclosure baseline.\n\n"
    "CYCLE 1 BASELINE (July Initial Disclosure):\n"
    "--------------------------------------------------------------------------------\n"
    "{july_baseline}\n"
    "--------------------------------------------------------------------------------\n\n"
    "EVALUATION RULES FOR CYCLE 1:\n"
    "1. Do NOT use or assume any technical details disclosed after July 2026 (e.g., August Postmortem facts).\n"
    "2. REASONING FIRST: Provide step-by-step reasoning explaining whether the claim aligns, contradicts, or is unbacked by the July text.\n"
    "3. CLASSIFY SECOND: Assign exactly one status label:\n"
    "   - 'Supported': Directly backed by the July text.\n"
    "   - 'Contradicted': Directly conflicts with or contradicts facts in the July text.\n"
    "   - 'Neither': Not backed by the July text, but does NOT explicitly contradict it (includes postmortem facts not yet known or general speculation).\n"
)

cycle_2_prompt_template = (
    "You are an expert qualitative researcher executing Cycle 2 of the YouTube AI Incident Framing Audit.\n"
    "Your task is to evaluate extracted video claims against the COMPLETE cumulative technical baseline (July Initial Disclosure + August Postmortem).\n\n"
    "CYCLE 2 CUMULATIVE BASELINE (July + August):\n"
    "--------------------------------------------------------------------------------\n"
    "{cumulative_baseline}\n"
    "--------------------------------------------------------------------------------\n\n"
    "EVALUATION RULES FOR CYCLE 2:\n"
    "1. Compare the claim against the complete ground truth record available after August 2026.\n"
    "2. REASONING FIRST: Provide step-by-step reasoning explaining whether the claim is confirmed, contradicted, or remains unbacked across the entire record.\n"
    "3. CLASSIFY SECOND: Assign exactly one status label:\n"
    "   - 'Supported': Directly backed by the cumulative ground truth text.\n"
    "   - 'Contradicted': Directly conflicts with or contradicts facts in the cumulative record.\n"
    "   - 'Neither': Remains unbacked by the full technical record (e.g., pure speculation or unverified external rumors).\n"
)


# ==============================================================================
# 3. INDIVIDUAL EVALUATION FUNCTIONS WITH RETRY HANDLING
# ==============================================================================
def run_cycle_1(claims_input, july_baseline_text, retries=3, delay=5):
    if pd.isna(claims_input) or not str(claims_input).strip():
        return None

    prompt = cycle_1_prompt_template.format(july_baseline=july_baseline_text)

    for attempt in range(retries):
        time.sleep(5)
        try:
            response = client.models.generate_content(
                model="gemini-3.1-flash-lite",
                contents=[prompt, f"EXTRACTED CLAIMS TO EVALUATE:\n{claims_input}"],
                config={
                    "response_mime_type": "application/json",
                    "response_json_schema": CycleAnalysis.model_json_schema(),
                },
            )

            return response.parsed
        except Exception as e:
            print(f"Cycle 1 Attempt {attempt + 1} failed: {e}")
            if attempt < retries - 1:
                time.sleep(delay * (attempt + 1))
            else:
                return None




# ==============================================================================
# 4. EXECUTION PIPELINE
# ==============================================================================
# Extract ground truth baselines from DataFrame rows
july_gt_text = str(ground_truth_df.iloc[0].values)
august_gt_text = str(ground_truth_df.iloc[1].values)
cumulative_gt_text = f"{july_gt_text}\n\n{august_gt_text}"

# Run Cycle 1 independently
print("Executing Cycle 1 Verification (July Baseline)...")
claims_df['cycle_1_results'] = claims_df['atomized_proposition'].apply(
    lambda claim: run_cycle_1(claim, july_gt_text)
)

Executing Cycle 1 Verification (July Baseline)...
Executing Cycle 2 Verification (August Baseline)...
Cycle 2 Attempt 1 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 30.513774975s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '30s'}]}}
Cycle 2 Attempt 2 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 20.439036214s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '20s'}]}}
Cycle 2 Attempt 3 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 5.374078836s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.1-flash-lite', 'location': 'global'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '5s'}]}}
Cycle 2 Attempt 1 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 307.675449ms.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '0s'}]}}
Cycle 2 Attempt 2 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 50.258012674s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.1-flash-lite', 'location': 'global'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
Cycle 2 Attempt 3 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 35.183332553s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '35s'}]}}
Cycle 2 Attempt 1 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 30.110851883s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '30s'}]}}
Cycle 2 Attempt 2 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 20.050570894s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.1-flash-lite', 'location': 'global'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '20s'}]}}
Cycle 2 Attempt 3 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 4.983893303s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}
Cycle 2 Attempt 1 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 59.889902304s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '59s'}]}}
Cycle 2 Attempt 2 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 49.80912493s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.1-flash-lite'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '49s'}]}}
Cycle 2 Attempt 3 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 34.736809155s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.1-flash-lite', 'location': 'global'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}
Cycle 2 Attempt 1 failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 500, model: gemini-3.1-flash-lite\nPlease retry in 29.672738957s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.1-flash-lite', 'location': 'global'}, 'quotaValue': '500'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '29s'}]}}

KeyboardInterrupt:

In [ ]:

client = genai.Client(api_key="AXXXXXX")

def run_cycle_2(claims_input, cumulative_baseline_text, retries=3, delay=5):
    if pd.isna(claims_input) or not str(claims_input).strip():
        return None

    prompt = cycle_2_prompt_template.format(cumulative_baseline=cumulative_baseline_text)

    for attempt in range(retries):
        print("success")
        time.sleep(4)

        try:

            response = client.models.generate_content(
                model="gemini-3.1-flash-lite",
                contents=[prompt, f"EXTRACTED CLAIMS TO EVALUATE:\n{claims_input}"],
                config={
                    "response_mime_type": "application/json",
                    "response_json_schema": CycleAnalysis.model_json_schema(),
                },
            )
            return response.parsed
        except Exception as e:
            print(f"Cycle 2 Attempt {attempt + 1} failed: {e}")
            if attempt < retries - 1:
                time.sleep(delay * (attempt + 1))
            else:
                return None


# Run Cycle 2 independently
print("Executing Cycle 2 Verification (August Baseline)...")
claims_df['cycle_2_results'] = claims_df['atomized_proposition'].apply(
    lambda claim: run_cycle_2(claim, cumulative_gt_text)
)

Executing Cycle 2 Verification (August Baseline)...
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success
success

In [ ]:
claims_df.iloc[0,:].cycle_1_results

{'evaluations': [{'claim_id': '001',
   'extracted_claim': 'An autonomous AI performed the first confirmed hack entirely on its own.',
   'reasoning': "The July baseline documents that models (specifically Internal Model 1) circumvented controls, exploited infrastructure, and accessed third-party systems. However, the text refers to these actions as part of a cybersecurity evaluation ('ExploitGym') where models were designed to find vulnerabilities in software and interact with internal/external systems. It does not characterize these activities as 'the first confirmed hack' by an autonomous AI, nor does it define the event in such a manner. The term 'first confirmed hack' is a specific framing not present in the provided text.",
   'status': 'Neither'}]}

In [ ]:
import json

# Helper functions to safely extract reasoning and status from Pydantic models or dicts
def extract_reasoning(result_obj):
    if result_obj is None or pd.isna(result_obj):
        return None
    # Handle Pydantic model response
    if hasattr(result_obj, 'evaluations') and result_obj.evaluations:
        return result_obj.evaluations[0].reasoning
    # Handle dictionary response
    if isinstance(result_obj, dict) and 'evaluations' in result_obj:
        evals = result_obj['evaluations']
        if isinstance(evals, list) and len(evals) > 0:
            return evals[0].get('reasoning')
    return None

def extract_status(result_obj):
    if result_obj is None or pd.isna(result_obj):
        return None
    # Handle Pydantic model response
    if hasattr(result_obj, 'evaluations') and result_obj.evaluations:
        return result_obj.evaluations[0].status
    # Handle dictionary response
    if isinstance(result_obj, dict) and 'evaluations' in result_obj:
        evals = result_obj['evaluations']
        if isinstance(evals, list) and len(evals) > 0:
            return evals[0].get('status')
    return None

# Parse Cycle 1 into dedicated columns (Reasoning FIRST, Status SECOND)
claims_df['cycle_1_reasoning'] = claims_df['cycle_1_results'].apply(extract_reasoning)
claims_df['cycle_1_status'] = claims_df['cycle_1_results'].apply(extract_status)

# Parse Cycle 2 into dedicated columns (Reasoning FIRST, Status SECOND)
claims_df['cycle_2_reasoning'] = claims_df['cycle_2_results'].apply(extract_reasoning)
claims_df['cycle_2_status'] = claims_df['cycle_2_results'].apply(extract_status)

# Preview the newly generated parsed columns
claims_df[['cycle_1_reasoning', 'cycle_1_status', 'cycle_2_reasoning', 'cycle_2_status']].head()

,cycle_1_reasoning,cycle_1_status,cycle_2_reasoning,cycle_2_status
0,The July baseline documents that models (speci...,Neither,The provided ground truth report states that t...,Neither
1,The baseline text states that the agents explo...,Neither,The technical record states that the AI agents...,Contradicted
2,The July 2026 disclosure states that OpenAI mo...,Neither,The ground truth documents from OpenAI describ...,Neither
3,The July disclosure confirms that OpenAI model...,Neither,The ground truth documents state that OpenAI m...,Contradicted
4,The July disclosure describes the event as an ...,Neither,The provided text describes the Hugging Face i...,Supported

In [ ]:
claims_df.columns

Index(['Entry_ID', 'Video_Title', 'Channel_Name', 'URL', 'Views',
       'exact_wording', 'atomized_proposition', 'claim_layer', 'claim_type',
       'framing_tags', 'cycle_1_results', 'cycle_2_results',
       'cycle_1_reasoning', 'cycle_1_status', 'cycle_2_reasoning',
       'cycle_2_status'],
      dtype='object')

In [ ]:
# Save claims_df with all extracted fields, reasoning, and status to CSV
claims_df.to_csv('verified_claims_results.csv', index=False)

print("Successfully exported claims_df to 'verified_claims_results.csv'!")

Successfully exported claims_df to 'verified_claims_results.csv'!

In [ ]:
claims_df.cycle_2_status.value_counts()

cycle_2_status
Neither         140
Supported       103
Contradicted     27
Name: count, dtype: int64